name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'deploy'
        options:
          - deploy
          - destroy

jobs:
  deploy_or_destroy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: "eu-west-1"
      S3_BUCKET_NAME: "terraform-backend"
      DYNAMODB_TABLE_NAME: "terraform-locks"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        run: |
          echo "Setting up AWS credentials..."
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log selected action
        run: echo "Selected action ${{ github.event.inputs.action }}"

      - name: Create S3 Bucket and DynamoDB Table for Terraform Backend
        run: |
            echo "Creating S3 bucket and DynamoDB table for Terraform backend..."
    
            # Create S3 bucket
            aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }} --region ${{ env.TF_VAR_aws_region }} --create-bucket-configuration LocationConstraint=${{ env.TF_VAR_aws_region }} || {
            if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
                echo "Bucket already exists"
              else
                echo "Failed to create S3 bucket"
                exit 1
              fi
            }
    
            # Create DynamoDB table
            aws dynamodb create-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
            --region ${{ env.TF_VAR_aws_region }} || {
                ERROR_CODE=$?
            if [ $ERROR_CODE -eq 400 ] && aws dynamodb describe-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} 2>/dev/null; then
                  echo "Table already exists"
                else
                  echo "Failed to create DynamoDB table with error code $ERROR_CODE"
                  exit 1
                fi
              }
    
            echo "S3 bucket and DynamoDB table setup complete."
        env:
          TF_VAR_aws_region: eu-west-1
          S3_BUCKET_NAME: terraform-backend
          DYNAMODB_TABLE_NAME: terraform-locks

      - name: Setup .NET
        if: ${{ github.event.inputs.action == 'deploy' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies and build
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
            echo "Restoring dependencies and building the project..."
            dotnet publish AWSLambdaProject/AWSLambdaProject.csproj -c Release -o ./publish
            if [ -d "./publish" ]; then
                echo "Project build complete and output directory exists."
            else
                echo "Build failed or output directory not found."
                exit 1
            fi
        working-directory: .

      - name: Zip artifacts
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
            echo "Zipping artifacts..."
            if [ -d "./publish" ]; then
              cd ./publish
              zip -r lambda-deployment-package.zip .
              echo "Artifacts zipped and ready for deployment."
            else
              echo "Publish directory not found."
              exit 1
            fi
        working-directory: .

      - name: Deploy Lambda using Terraform
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          echo "Deploying Lambda using Terraform..."
          cd ./terraform
          terraform init
          terraform apply -auto-approve
          echo "Terraform deployment complete."
        env:
          TF_VAR_aws_region: ${{ env.TF_VAR_aws_region }}

      - name: Destroy Lambda using Terraform
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          echo "Destroying Lambda using Terraform..."
          cd ./terraform
          terraform init
          terraform destroy -auto-approve
          echo "Terraform destruction complete."
        env:
          TF_VAR_aws_region: ${{ env.TF_VAR_aws_region }}

      - name: Delete S3 Bucket and DynamoDB Table
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          echo "Deleting S3 bucket and DynamoDB table for Terraform backend..."
          aws s3 rb s3://${{ env.S3_BUCKET_NAME }} --force
          aws dynamodb delete-table --table-name ${{ env.DYNAMODB_TABLE_NAME }} --region ${{ env.TF_VAR_aws_region }}
          echo "S3 bucket and DynamoDB table deleted."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.TF_VAR_aws_region }}
